#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

sudo echo $$ >> /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command" sudo rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done