#!/usr/bin/env bash
# This script configures and ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sed -i 's/127.0.0.1/127.0.0.2' /etc/hosts  
sed -i '2i8.8.8.8	facebook.com' /etc/hosts

